// Auto-generated by @btc/auto-discover
declare module 'virtual:@btc/auto/routes' {
  export const routes: any[]
  export default routes
}

declare module 'virtual:@btc/auto/apis' {
  export const apis: Record<string, { base?: string; devPort?: number }>
  export function apiOf(id: string): { base?: string; devPort?: number }
  export default apis
}

declare module 'virtual:@btc/auto/meta' {
  const meta: any
  export default meta
}
